version: '3.8'
volumes:
  etcd-data-1: null
  etcd-data-2: null
  etcd-data-3: null
  patroni-pg-data-1: null
  patroni-pg-data-2: null
  patroni-pg-data-3: null
services:
  etcd1:
    build: ./patroni
    command: etcd -name etcd1 -initial-advertise-peer-urls http://etcd1:2380
    env_file: patroni/docker/etcd.env
    hostname: etcd1
    image: 127.0.0.1:3333/patroni
    volumes:
    - etcd-data-1:/home/postgres
  etcd2:
    build: ./patroni
    command: etcd -name etcd2 -initial-advertise-peer-urls http://etcd2:2380
    env_file: patroni/docker/etcd.env
    hostname: etcd2
    image: 127.0.0.1:3333/patroni
    volumes:
    - etcd-data-2:/home/postgres
  etcd3:
    build: ./patroni
    command: etcd -name etcd3 -initial-advertise-peer-urls http://etcd3:2380
    env_file: patroni/docker/etcd.env
    hostname: etcd3
    image: 127.0.0.1:3333/patroni
    volumes:
    - etcd-data-3:/home/postgres
  haproxy:
    build: ./patroni
    command: haproxy
    env_file: patroni/docker/patroni.env
    hostname: haproxy
    image: 127.0.0.1:3333/patroni
    ports:
      - 55555:5000
  patroni1:
    build: ./patroni
    env_file: patroni/docker/patroni.env
    environment:
      PATRONI_NAME: patroni1
      PATRONI_POSTGRES_PORT: '5432'
      PATRONI_POSTGRES_YML: postgres0.yml
      PATRONI_RESTAPI_PORT: '8008'
    hostname: patroni1
    image: 127.0.0.1:3333/patroni
    volumes:
    - patroni-pg-data-1:/home/postgres
  patroni2:
    build: ./patroni
    env_file: patroni/docker/patroni.env
    environment:
      PATRONI_NAME: patroni2
      PATRONI_POSTGRES_PORT: '5433'
      PATRONI_POSTGRES_YML: postgres1.yml
      PATRONI_RESTAPI_PORT: '8009'
    hostname: patroni2
    image: 127.0.0.1:3333/patroni
    volumes:
    - patroni-pg-data-2:/home/postgres
  patroni3:
    build: ./patroni
    env_file: patroni/docker/patroni.env
    environment:
      PATRONI_NAME: patroni3
      PATRONI_POSTGRES_PORT: '5434'
      PATRONI_POSTGRES_YML: postgres2.yml
      PATRONI_RESTAPI_PORT: '8010'
    hostname: patroni3
    image: 127.0.0.1:3333/patroni
    volumes:
    - patroni-pg-data-3:/home/postgres